steps:
# - name: gcr.io/cloud-builders/gsutil
#   id: copy-m2-repo-from-gcs
#   args: ['cp', '-c', 'gs://m2c-demo-maven-cache/true-demo-repository.zip', '/workspace/true-demo-repository.zip']
# - name: joshkeegan/zip:latest
#   id: unzip 
#   script: '[ -f "/workspace/true-demo-repository.zip" ] && unzip "/workspace/true-demo-repository.zip" -d /workspace/.m2/repository' 
- name: maven:3-eclipse-temurin-17
  id: maven-build
  entrypoint: mvn
  args: ['test', '-Dmaven.repo.local=/workspace/.m2/repository']
- name: alpine
  id: chmod 
  script: 'chmod -R 777 /workspace/.m2'
- name: gcr.io/k8s-skaffold/pack
  id: buildpack
  entrypoint: pack
  args:
  - build
  - us-central1-docker.pkg.dev/m2c-demo/container/true-demo:latest
  - --builder
  - paketobuildpacks/builder:base
  - --cache-image
  - us-central1-docker.pkg.dev/m2c-demo/container/true-demo-cache:latest
  - --volume
  - /workspace/.m2:/home/cnb/.m2:rw
  - --publish
- name: joshkeegan/zip:latest
  id: zip 
  script: 'zip -r /workspace/true-demo-repository.zip /workspace/.m2/repository' 
- name: gcr.io/cloud-builders/gsutil
  id: copy-m2-repo-to-gcs
  args: ['cp', '/workspace/true-demo-repository.zip', 'gs://m2c-demo-maven-cache/true-demo-repository.zip']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: deploy
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'true-demo'
  - '--image'
  - 'us-central1-docker.pkg.dev/m2c-demo/container/true-demo:latest'
  - '--region'
  - 'us-central1'
