steps:
# maven test 
- name: maven:3-eclipse-temurin-17
  entrypoint: mvn
  args: ['test', '-Dmaven.repo.local=/workspace/.m2']
- name: alpine
  script: 'chmod -R 777 /workspace/.m2'
- name: gcr.io/k8s-skaffold/pack
  entrypoint: pack
  args:
  - build
  - us-central1-docker.pkg.dev/m2c-demo/container/true-demo:latest
  - --builder
  - paketobuildpacks/builder:base
  - --cache-image
  - us-central1-docker.pkg.dev/m2c-demo/container/true-demo-cache:latest
  - --volume
  - /workspace/.m2:/home/cnb/.m2:rw
  - --publish
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'true-demo'
  - '--image'
  - 'us-central1-docker.pkg.dev/m2c-demo/container/true-demo:latest'
  - '--region'
  - 'us-central1'
