apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: true-pipeline
serialPipeline:
  stages:
  - targetId: true-demo-dev
    profiles:
    - true-demo-dev
  - targetId: true-demo-prod
    profiles:
    - true-demo-prod
    strategy:
      canary:
        runtimeConfig:
          cloudRun:
            automaticTrafficControl: true
        canaryDeployment:
          percentages: [25, 50, 75]
          verify: true