apiVersion: skaffold/v4beta8
kind: Config
build:
  artifacts:
  - image: us-central1-docker.pkg.dev/m2c-demo/container/true-demo
    buildpacks:
      builder: 'paketobuildpacks/builder:base'
      volumes: 
      - host: '/workspace/.m2'
        target: '/home/cnb/.m2'
        options: 'rw'
profiles:
- name: true-demo-k8s-dev
  manifests: 
    rawYaml:
    - k8s/*.yaml
  deploy:
    kubectl: {}
