apiVersion: skaffold/v4beta8
kind: Config
build:
  artifacts:
  - image: us-central1-docker.pkg.dev/m2c-demo/container/true-demo
    jib: {}
    sync: 
      auto: true
manifests:
  rawYaml:
    - k8s/*.yml
deploy:
  kubectl: {}
portForward:
- resourceType: deployment
  resourceName: true-k8s-demo
  port: 8080
  localPort: 8080
