apiVersion: skaffold/v4beta8
kind: Config
build:
  artifacts:
  - image: us-central1-docker.pkg.dev/m2c-demo/container/true-demo
    jib: {}
    sync: 
      auto: true
manifests:
  rawYaml:
    - cloud-run/*.yaml
deploy:
  cloudrun:
    projectid: m2c-demo
    region: us-central1
portForward:
  - resourceType: service
    resourceName: true-demo-dev
    localPort: 8080