apiVersion: apps/v1
kind: Deployment
metadata:
  name: true-k8s-demo
  namespace: true-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: true-k8s-demo
  template:
    metadata:
      labels:
        app: true-k8s-demo
    spec:
      containers:
      - name: true-k8s-demo
        image: us-central1-docker.pkg.dev/m2c-demo/container/true-demo
        ports:
        - containerPort: 8080
        resources:
          limits:
            # cpu: 500m
            memory: 1Gi
          requests:
            # cpu: 1000m
            memory: 1Gi
---
# service.yml
# apiVersion: v1
# kind: Service
# metadata:
#   name: true-k8s-demo
# spec:
#   type: LoadBalancer
#   selector:
#     app: true-k8s-demo
#   ports:
#   - port: 8080