apiVersion: apps/v1
kind: Deployment
metadata:
  name: true-k8s-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: true-k8s-demo
  template:
    metadata:
      labels:
        app: true-k8s-demo
    spec:
      containers:
      - name: true-k8s-demo
        image: us-central1-docker.pkg.dev/m2c-demo/cloud-run-source-deploy/true-demo-2@sha256:5b5a8a797731347b3496824b27f577c320c97e2a9754ab97aa6bb957e8d04bd7
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 1000m
            memory: 1Gi
---
# service.yml
apiVersion: v1
kind: Service
metadata:
  name: true-k8s-demo
spec:
  type: LoadBalancer
  selector:
    app: true-k8s-demo
  ports:
  - port: 8080